from abc import ABC, abstractmethod
from typing import Any, List


class IList(ABC):
	@abstractmethod
	def Add(self, value: Any) -> int: ...
	@abstractmethod
	def Clear(self) -> None: ...
	@abstractmethod
	def Contains(self, value: Any) -> bool: ...
	@abstractmethod
	def IndexOf(self, value: Any) -> int: ...
	@abstractmethod
	def Insert(self, index: int, value: Any) -> None: ...
	@abstractmethod
	def Remove(self, value: Any) -> None: ...
	@abstractmethod
	def RemoveAt(self, index: int) -> None: ...

	@abstractmethod
	@property
	def IsFixedSize(self) -> bool: ...
	@abstractmethod
	@property
	def IsReadOnly(self) -> bool: ...

	@abstractmethod
	def __getitem__(self, index: int) -> Any: ...
	@abstractmethod
	def __setitem__(self, index: int, value: Any) -> None: ...

class ICollection(ABC):
	@abstractmethod
	def CopyTo(self, array: List, index: int) -> None: ...

	@abstractmethod
	@property
	def Count(self) -> int: ...
	@abstractmethod
	@property
	def IsSynchronized(self) -> bool: ...
	@abstractmethod
	@property
	def SyncRoot(self) -> object: ...

class IEnumerator(ABC):
	@abstractmethod
	@property
	def Current(self) -> Any: ...

	@abstractmethod
	def MoveNext(self) -> bool: ...
	@abstractmethod
	def Reset(self) -> None: ...

class IEnumerable(ABC):
	@abstractmethod
	def GetEnumerator(self) -> IEnumerator: ...