"""
https://learn.microsoft.com/en-us/dotnet/api/Microsoft.Win32
"""

from abc import ABC, abstractmethod
from typing import overload

from System import Array, Object
from System.Windows import Window

class CommonDialog(Object, ABC):
	# incomplete
	@overload
	def ShowDialog(self) -> bool: ...
	@overload
	def ShowDialog(self, owner: Window) -> bool: ...

class CommonItemDialog(CommonDialog, ABC):
	# incomplete
	@property
	def Title(self) -> str: ...
	@Title.setter
	def Title(self, value: str) -> None: ...
	@property
	def InitialDirectory(self) -> str: ...
	@InitialDirectory.setter
	def InitialDirectory(self, value: str) -> None: ...

class FileDialog(CommonItemDialog, ABC):
	# incomplete
	@property
	def FileName(self) -> str: ...
	@FileName.setter
	def FileName(self, value: str) -> None: ...
	@property
	def FileNames(self) -> Array[str]: ...
	@property
	def CheckFileExists(self) -> bool: ...
	@CheckFileExists.setter
	def CheckFileExists(self, value: bool) -> None: ...
	@property
	def CheckPathExists(self) -> bool: ...
	@CheckPathExists.setter
	def CheckPathExists(self, value: bool) -> None: ...
	@property
	def Filter(self) -> str: ...
	@Filter.setter
	def Filter(self, value: str) -> None: ...
	@property
	def FilterIndex(self) -> int: ...
	@FilterIndex.setter
	def FilterIndex(self, value: int) -> None: ...
	@property
	def AddExtension(self) -> bool: ...
	@AddExtension.setter
	def AddExtension(self, value: bool) -> None: ...

class OpenFileDialog(FileDialog):
	# incomplete
	@property
	def Multiselect(self) -> bool: ...
	@Multiselect.setter
	def Multiselect(self, value: bool) -> None: ...

class SaveFileDialog(FileDialog):
	# incomplete
	@property
	def CreatePrompt(self) -> bool: ...
	@CreatePrompt.setter
	def CreatePrompt(self, value: bool) -> None: ...
	@property
	def OverwritePrompt(self) -> bool: ...
	@OverwritePrompt.setter
	def OverwritePrompt(self, value: bool) -> None: ...
	@property
	def CreateTestFile(self) -> bool: ...
	@CreateTestFile.setter
	def CreateTestFile(self, value: bool) -> None: ...

class OpenFolderDialog(CommonItemDialog):
	# incomplete
	@property
	def FolderName(self) -> str: ...
	@FolderName.setter
	def FolderName(self, value: str) -> None: ...
	@property
	def FolderNames(self) -> Array[str]: ...
	@property
	def Multiselect(self) -> bool: ...
	@Multiselect.setter
	def Multiselect(self, value: bool) -> None: ...
